apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api-deploy-pubsub
  labels:
    app: nodejs-api-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-api-pubsub
  template:
    metadata:
      labels:
        app: nodejs-api-pubsub
        #gcp-auth-skip-secret: "true"
    spec:
      containers:
      - name: nodejs-api
        image: 499092/luisgamarra:node-app-pubsub
        imagePullPolicy: IfNotPresent
        #ports:
         # - containerPort: 3000
        env:
        - name: PORT
          value: "3008"
        - name: TOPIC
          value: "topic-dummy"
        - name: GOOGLE_CLOUD_PROJECT
          value: "eventos-319419"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/opt/secrets/credentials.json"
        volumeMounts:
        - name: test
          mountPath: "/opt/secrets"
          readOnly: true
      volumes:
      - name: test
        secret:
          secretName: credentials-secret
          items:
            - key: sa_json
              path: credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service-pubsub
  labels:
    app: nodejs-api-pubsub
spec:
  type: NodePort
  selector:
    app: nodejs-api-pubsub
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 3008
